services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: eventlogger-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=EventLogger123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init/SQLServer/init.sql:/init.sql
      - ./init/SQLServer/init.sh:/init.sh
    networks:
      - eventlogger-network
    command: ["/bin/bash", "/init.sh"]


  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: eventlogger-dynamodb
    command: "-jar DynamoDBLocal.jar -sharedDb"
    ports:
      - "8000:8000"
    networks:
      - eventlogger-network
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-west-2
    volumes:
    - dynamo-data:/home/dynamodblocal/data

  dynamodb-init:
    image: amazon/aws-cli
    depends_on:
      - dynamodb
    entrypoint: ["/bin/sh", "-c"]
    command: >
       -c "
       sleep 5 &&
       aws dynamodb create-table --table-name EventDetails \
       --attribute-definitions AttributeName=UserId,AttributeType=S AttributeName=Timestamp,AttributeType=S \
       --key-schema AttributeName=UserId,KeyType=HASH AttributeName=Timestamp,KeyType=RANGE \
       --billing-mode PAY_PER_REQUEST \
       --endpoint-url http://dynamodb:8000 \
       --region us-west-2 || echo 'Table may already exist'"
    networks:
      - eventlogger-network
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-west-2


volumes:
  sqlserver_data:
  dynamo-data:

networks:
  eventlogger-network:
    external: true
    driver: bridge 