AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: EventLogger API - Serverless .NET API

# TODO: Configure global settings for your Lambda functions
# Consider: Runtime, Timeout, MemorySize, Environment variables, etc.

Parameters:
  Environment:
    Type: String
    Default: Development

Resources:
  EventLoggerApiFunction:
    Type: AWS::Serverless::Function
    Properties:     
      PackageType: Zip
      Runtime: dotnet8
      CodeUri: src/EventLogger.Api/
      Handler: EventLogger.Api::EventLogger.Api.LambdaEntryPoint::FunctionHandlerAsync
      Timeout: 30
      Events:
        ApiRoot:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          ASPNETCORE_ENVIRONMENT: "Development"

# TODO: Add outputs to expose your API endpoint URL
Outputs:
  # Add meaningful outputs for your API 